### ISSUE TITLE
Ore Refiner compatibility

### ISSUE THREAD

**Issue by lukaarma** [Lykrast/ProdigyTech#10]
Lead ore from Embers Rekindled can't be refined in the machine

**Comment by Lykrast** [comment]
Check 2 things:

* Is the ore correctly oredicted as `oreLead`?
* Is there Lead Dust in your instance?

That is what the machines are looking for. If the ore isn't oredicted properly then it's a Embers issue.

You can test that everything is working by adding something that adds Lead Dust like Base Metals or Thermal Foundation, making an new world and checking if the recipe is there, then removing that mod.

**Comment by lukaarma** [comment]
Ok will do as soon as I can, thanks for responding so fast!

Il gio 18 lug 2019, 09:38 Lykrast <notifications@github.com> ha scritto:

**Comment by lukaarma** [comment]
Ok i made some test and turns out that the issue was what you suggested, so thanks for the help!
