### ISSUE TITLE
config ash output

### ISSUE THREAD

**Issue by majijn** [Lykrast/ProdigyTech#16]
would it be possible for the type of ash we get can be chosen ? i have a couple of kinds of ash and my braziers of hoarding would handle just one type of ash better

really enjoying the mod btw!

**Comment by Lykrast** [comment]
I'm not planning on adding something like this, you can circumvent the issue by simply making your ash only one way.

If some mods are picky and only want one type of ash despite their ash also working for the other mods that want ash (through the `dustAsh` oredict), you can report the issue to them. Although now that 1.14 is well out they might not want to fix it for an older version.

At worst get yourself CraftTweaker and add a simple Ash to Ash recipe.
