### ISSUE TITLE
[suggestion] refrigerator, freezer

### ISSUE THREAD

**Issue by majijn** [Lykrast/ProdigyTech#18]
im not entirely sure how the refrigerator would need to work, but maybe it could take heat from below , and give out negative heat above it? or maybe it works normally from bottom to top with hot air, and it chills a block on one of its lateral sides, perhaps that way powering the freezer (and maybe giving more heat above it than it started with, if the freezer also needs positive heat from below)

freezer to get some ways of making snow layers, snowballs , snow blocks , ice and packed ice.

**Comment by Lykrast** [comment]
I thought about a Freezer several times but I never managed to think of enough item -> item recipes. In case you haven't noticed, Prodigy Tech does not use fluids, and a Freezer would need fluids as input to make sense.

So in short, no.

**Comment by majijn** [comment]
one of the options i thought was that it created the snow in-world, hence youre not working with fluids in a direct way. just condensation (thats why i was thinking snow layers at first, i shouldve mentioned that)

 i guess 
same could be applied to in-world sourceblocks of water into ice if its cold enough.
