### ISSUE TITLE
[Suggestion] Making the explosion furnace even more fun to automate

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Lykrast/ProdigyTech#2]
I'd like to request a few changes to the explosion furnace. These will make automating it more complex, and way more fun to watch. Alternatively the current furnace could stay, and this could be turned into a higher tier furnace.

1. Rather than adding gunpowder and sand to the GUI, have the crafting process trigger whenever a block of TNT explodes within 3 blocks of the furnace.

2. The block is 100% explosion proof

3. The block is not compatible with hoppers or item pipes. Instead, you must drop items onto it in item entity form. Compatible items will be absorbed if they're in the block space directly above the explosion furnace.

4. When the product is complete, the output items are dropped from below it in item entity form.

5. The block no longer responds to a redstone signal. Instead it attempts to craft when it experiences an explosion.

6. If the block is too far away from the explosion, it will do nothing.

Automating this would be a very unique challenge. If the items aren't dropped correctly, they will be destroyed by the explosion. You also need a collection system of some sort.

As a bonus, multiple explosion furnaces could be powered by a single TNT block, making it cheaper to run. This gives a nice secondary puzzle as players would be encouraged to run as many blocks as possible on a single explosion.

**Comment by Lykrast** [comment]
Even though this sounds like a great idea, I'm personally not a fan of that type of mechanic and will very likely never add something like that in Prodigy Tech.

However this would fit a Botania addon perfectly.
