### ISSUE TITLE
[ Question ] Primordials Reactor

### ISSUE THREAD

**Issue by HurtsAsHell** [Lykrast/ProdigyTech#5]
There are a method to improve the speed and the efficiency of that machinery?

**Comment by Lykrast** [comment]
Yes, as stated in both its description and the book, feeding it different plants at the same time makes it more efficient.

Any item it shows in JEI is considered a different plant, even if it's on the same entry (for example Oak Saplings and Birch Saplings are considered different, despite both being `treeSapling`).

You can see exactly how it gets affected on this [table on the FTB wiki](https://ftb.gamepedia.com/Primordialis_Reactor). You can see with only 5 different items you can already cut down the cost by about 5 and the time by 24.

Lastly, like all other machines, feeding it hotter air will make it faster. Double the input temperature and it'll work at double the speed and so on.
