### ISSUE TITLE
[request] pregrinder/sawmill method of obtaining sawdust

### ISSUE THREAD

**Issue by majijn** [Lykrast/ProdigyTech#9]
otherwise when starting in biomes/dimensions where creepers dont spawn means you cannot start with the mod earlygame

**Comment by Lykrast** [comment]
All overworld biomes, including all skyblocks I know of, have Creepers in them, a way to make Creepers spawn or a recipe to make Gunpowder.

If you added mods to explicitely change the starting location to one that doesn't have Creepers or any recipe for Gunpowder or the other explosives, just like for tech mods that can't start without Copper, then it's up to you (or whoever made the pack) to add an alternative way to start.

You can do that by adding recipe for Gunpowders but also by adding other explosives to the Explosion Furnace, or even make an alternate less efficient recipe for Ferramic.
